/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configurator;

import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;
import javax.swing.plaf.basic.BasicSliderUI;

/**
 *
 * @author cherepanov
 */
public class Main_JPanel extends javax.swing.JFrame {

    /**
     * Creates new form Main_JPanel
     */
    public Main_JPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("NewProject");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jButton1)
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        FrameCreate fc=new FrameCreate();
//        JFrame.setDefaultLookAndFeelDecorated(true);
//        JFrame frame = new JFrame();
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        JTextField text1, text2, text3;
//        JLabel label;
//        JButton button;
//
//        frame.setLayout(new FlowLayout(FlowLayout.CENTER));
//
//        Toolkit kit = Toolkit.getDefaultToolkit();//поработать над расположением экрана
//        Dimension screen = kit.getScreenSize();
//        int screenHeight = screen.height;
//        int screenWidght = screen.width;
//        frame.setLocation(screenHeight / 2, screenWidght / 2);
//
//        label = new JLabel("Test label");
//        text1 = new JTextField("User", 25);
//        text2 = new JTextField("Pass", 25);
//        text3 = new JTextField("Path to project", 25);
//
//        frame.add(label);
//        frame.add(text1);
//        frame.add(text2);
//        frame.add(text3);
//        frame.add(button = new JButton("Action"));
//
//        frame.setPreferredSize(new Dimension(500, 150));
//
//        frame.pack();
//        frame.setVisible(true);
//        
//        
       
        


    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_JPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
