/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package basepostgresluaxls;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nazarov
 */
public class FrameTable extends javax.swing.JPanel {

        BasePostgresLuaXLS workbase = new BasePostgresLuaXLS(); // подключаем нашу базу

    /**
     * Creates new form Panel
     */
    public FrameTable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(getTableData());
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("To_Lua_DRV");
        jButton1.setToolTipText("Формируем файл луа для драйверов");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(881, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(468, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(40, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser fileopen = new JFileChooser("C:\\Users\\Nazarov\\Desktop\\Info_script_file_work\\_actual_config\\Config\\Design\\IO_XLS\\GPA");
        int ret = fileopen.showDialog(null, "Открыть файл(DRV_from_base_LUA)");                
        if (ret == JFileChooser.APPROVE_OPTION) {
        File file = fileopen.getSelectedFile();
        //System.out.print(file.getPath());
        String currentT = StructSelectData.getnTable();
        
        ArrayList<String[]> dataFromDb = new ArrayList<>();
        workbase.connectionToBase();
        //dataFromDb = workbase.selectData("ai1");
        dataFromDb = workbase.selectData(currentT);
        System.out.println("This Table  -->" + currentT);
        //Сформировать файл луа новый файл
        CreateFileIO_AILUA maks_file = new CreateFileIO_AILUA();
               try {
                   maks_file.writeDataMaksFile(dataFromDb, file.getPath()); // такое себе но требуют результат
               } catch (IOException ex) {
                   Logger.getLogger(FrameTable.class.getName()).log(Level.SEVERE, null, ex);
               }
            
        javax.swing.JOptionPane.showMessageDialog(null,"Данные из базы в файл Максима" + file.getPath() + " загружены"); //диалоговое окно

        
        }  
        
    }//GEN-LAST:event_jButton1ActionPerformed

 TableModel getTableData(){ // функция для создания списка из талиц базы так же возращаем объект для конструкции таблицы при запуске
    // Можно так сложно не соединять, аппендицит от предыдущего что бы не запутаться
    String[] columnDop = {"Выбор"};// до поля для галок или еще чего
    String[] columnNames = StructSelectData.getColumns();
    String[] resultColumn = Stream.concat( Arrays.stream(columnDop), Arrays.stream(columnNames))
            .toArray(String[]::new); // соединяем два массива
    Object[][] data = StructSelectData.getcurrentSelectTable(); // От куда беру данные
    Object[] streamArray ;
    Object[] streamNull = new Object[1];
    streamNull[0] = null;
    Object[][] tmp2 = new Object[data.length][];
    for(int i=0; i< data.length; i++){
        streamArray = new Object[data[i].length+1];
        // преобразовываем массив
        Object[] testStream = Stream.concat( Arrays.stream(streamNull), Arrays.stream(data[i])).toArray(Object[]::new); 
        tmp2[i] = testStream;
    }
    return new DefaultTableModel(tmp2, resultColumn){  
    @Override           
    public Class<?> getColumnClass(int columnIndex) { // структура для отображения таблицы с галками
      Class clazz = String.class;
      switch (columnIndex) {
        case 0:
          clazz = Boolean.class;
          break;
      }
      return clazz; 
    }       
    @Override
    public boolean isCellEditable(int row, int column) {
      return column == column;
    } 
     @Override
    public void setValueAt(Object aValue, int row, int column) {
      // Условие проверки галочки скрывать легенду
      if (aValue instanceof Boolean && column == 0) {
        System.out.println("Posution - > " + row + " " + aValue);        
        Vector rowData = (Vector)getDataVector().get(row); // не помню для чего но без этого только скрывает =(
        rowData.set(0, (boolean)aValue);
        fireTableCellUpdated(row, column);
        
        try {
            // Само действие не реализованно
        if((boolean) aValue == true){
          System.out.println("true");
        }
        if((boolean) aValue == false){
          System.out.println("false");
        }
        }catch (NullPointerException e) {
        JOptionPane.showMessageDialog(null, "Трудности с добавлением");
        }
      }

    }
    };
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}


