/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrameCreate;

import ReadWriteExcel.ExcelAdapter;
import Tools.FileManager;
import Tools.MyTableModel;
import Tools.RegistrationJFrame;
import Tools.SaveFrameData;
import Tools.TableTools;
import Tools.closeJFrame;
import Tools.isCange;
import globalData.globVar;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

public class ChangerTagNamed extends javax.swing.JFrame {
    FileManager fm = new FileManager();
    MyTableModel tableModel; // модель таблицы
    ArrayList<String[]> fromDB; // Что получим из базы
    int tableSize = 0;
    int qCol = 0;
    ArrayList<String[]> newName;
    ArrayList<JFrame> listJF = new ArrayList();
    JPopupMenu popupMenu = new JPopupMenu();
    ArrayList<String[]> listItemList = new ArrayList<>();
    String tableName;
    String comment;
    
   
    public ChangerTagNamed(String table) {
        if (!globVar.DB.isConnectOK()) {
            return;
        }
        newName = new ArrayList<>();
        tableModel = new MyTableModel(newName);
        List<String> listColumn = new ArrayList<>(Arrays.asList("Наименование", "TAG_NAME_PLC"));//получили лист 
        if (listColumn == null || listColumn.isEmpty()) {
            return;
        }
        String[] cols = listColumn.toArray(new String[listColumn.size()]);//преобразовали лист в стринговый массив
        tableModel.setColumnIdentifiers(new String[]{"Наименование", "TAG_NAME_PLC", "Новое_Наименование", "New_TAG_NAME_PLC"});

        fromDB = globVar.DB.getData(table, cols);//получили данные из БД
        fromDB.forEach((rowData) -> tableModel.addRow(Stream.concat(Arrays.stream(rowData), Arrays.stream(new String[]{"", ""})).toArray(String[]::new)));//вставляем данные по ячейкам в таблицу
        comment = globVar.DB.getCommentTable(table);
        tableSize = fromDB.size();//размер строк
        qCol = listColumn.size();//размер столбцов
        int[] align = new int[qCol];
        int[] colsWidth = new int[qCol];

        TableTools.setWidthCols(cols, tableModel, colsWidth, 7.8);
        if (tableSize > 0) {
            TableTools.setAlignCols(fromDB.get(0), align);
        }

        initComponents();

        RegistrationJFrame rgf = (JFrame jf) -> {
            listJF.add(jf);
        };
        closeJFrame cjf = () -> {
            for (JFrame jf : listJF) {
                jf.setVisible(false);
            }
        };

      //  TableTools.setPopUpMenu(jTable1, popupMenu, tableModel, table, rgf, listJF);
        // TableTools.setTableSetting(jTable1, colsWidth, align, 25);
        
       
        
        jTable1.setRowSelectionAllowed(true);           // Разрешаю выделять по строкам
        TableColumnModel columnModel = jTable1.getColumnModel();
        
//         DefaultTableCellRenderer defaultTableCellRenderer = new DefaultTableCellRenderer();
//        System.setProperty("myColor", "0XEEEEEE");
//        defaultTableCellRenderer.setBackground(Color.getColor("myColor")); //задаем цвет столбца
//        columnModel.getColumn(0).setCellRenderer(defaultTableCellRenderer);
//        columnModel.getColumn(1).setCellRenderer(defaultTableCellRenderer);
        
        columnModel.setColumnSelectionAllowed(true);    // Разрешение выделения столбца
        columnModel.getSelectionModel().setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);// Режим выделения интервала
        int qCol = jTable1.getColumnCount();                //Определяю количество столбцов
        if (qCol > colsWidth.length) {
            qCol = colsWidth.length;  //чтобы не вылететь за границы таблицы, если переданный массив ширин неправильный
        }

        ExcelAdapter editT = new ExcelAdapter(jTable1);//редактирование таблицы контрл В Ц

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(tableModel);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Переименовать");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (String[] s : newName) {
            System.out.println(s.toString());
        }

        fm.ChangeIntTypeFile(globVar.desDir, newName);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangerTagNamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangerTagNamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangerTagNamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangerTagNamed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ChangerTagNamed().setVisible(true);
            }
        });
    }

    boolean compareTable(ArrayList<String[]> fromDB, DefaultTableModel tableModel) {
        int x = tableModel.getColumnCount();
        int y = tableModel.getRowCount();
        if (fromDB.size() != y || fromDB.get(0).length != x) {
            return true;
        }
        for (int i = 0; i < y; i++) {
            for (int j = 0; j < x; j++) {
                if (!fromDB.get(i)[j].equals(tableModel.getValueAt(i, j))) {
                    return true;
                }
            }
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
